version: "3.8"
services:
  mysqlcms:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  cmsmadesimple:
    container_name: cmsmadesimple
    build: CMSmadesimple/.
    ports:
      - "8000:8000"
    depends_on:
      - mysqlcms
    networks:
      - backend
    links:
      - mysqlcms:mysql

  vitrine:
    container_name: vitrine
    build:
      context: vitrine/.
    environment:
      NODE_ENV: production
    ports:
      - "10000:10000"
    networks:
      - backend

  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - cmsmadesimple
      - vitrine
    networks:
      - frontend
      - backend

volumes:
  mysql-data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
