---
- name: Update and upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Install necessary packages
  ansible.builtin.apt:
    name: "{{ packages_to_install }}"
    state: present

- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Enable automatic security updates
  ansible.builtin.copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Download-Upgradeable-Packages "1";
      APT::Periodic::AutocleanInterval "7";
      APT::Periodic::Unattended-Upgrade "1";
    dest: /etc/apt/apt.conf.d/20auto-upgrades

############ Install Docker ############

- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_installed
  ignore_errors: true

- name: Install necessary packages
  when: docker_installed is failed
  ansible.builtin.apt:
    name:
      - ca-certificates 
      - curl
      - gnupg
    state: latest
    update_cache: yes

- name: Add GPG key
  when: docker_installed is failed
  ansible.builtin.shell:
    cmd: |
      sudo install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      sudo chmod a+r /etc/apt/keyrings/docker.gpg

- name: Add the repository to Apt sources
  when: docker_installed is failed
  ansible.builtin.shell:
    cmd: |
      echo \
      "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
      "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install Docker packages
  when: docker_installed is failed
  ansible.builtin.apt:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: latest
    update_cache: yes
